name: inflection2
version: 0.4.3
environment:
  sdk: ">=1.8.0 <3.0.0"
authors:
  - Tobe O <thosakwe@gmail.com>
  - George Moschovitis <george.moschovitis@gmail.com>
description: Grammatical Inflection encoders.
homepage: https://github.com/thosakwe/dart-inflection
dev_dependencies:
  test: any
